"""Deterministic, offline recipe reports backed by retained benchmark artifacts."""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import math
import os
from pathlib import Path
import re
import sys
import tempfile
import tomllib
from urllib.parse import quote, urlsplit


SCHEMA = "anvil-serving.benchmark-recipe-catalog/v1"
REPORT_SCHEMA = "anvil-serving.benchmark-recipe-report/v1"
MAX_BYTES = 8 * 1024 * 1024
DECISIONS = {"current", "rollback", "challenger", "no-promotion", "rejected"}
MARKER = "<!-- Generated by eval benchmark report; edit the catalog and retained evidence. -->"
IDENTITY_FIELDS = ("model", "engine", "gpu", "measurement_protocol", "concurrency", "context_tokens", "max_tokens", "prompt_cache_mode", "request_canaries", "response_words", "controlled_output_policy", "shared_prefix_tokens")
LEGACY_OPTIONAL_FIELDS = {"response_words", "controlled_output_policy", "shared_prefix_tokens"}


def _metric_contract(path):
    if path == "metrics.throughput_tok_s":
        return "Aggregate output", "tok/s"
    families = {"ttft": ("TTFT", "ms"), "e2e": ("E2E", "ms"),
                "tpot": ("TPOT (mean ITL proxy)", "ms/token"),
                "decode_tok_s": ("Decode", "tok/s"),
                "effective_prefill_tok_s": ("Effective prefill", "tok/s")}
    for prefix, (label, unit) in families.items():
        for statistic in ("mean", "min", "p25", "p50", "p75", "p90", "p95", "p99", "max"):
            suffix = "_ms" if prefix in {"ttft", "e2e", "tpot"} else ""
            if path == f"metrics.{prefix}_{statistic}{suffix}":
                return f"{label} {statistic.upper() if statistic.startswith('p') else statistic}", unit
    raise ValueError("unsupported metric path; use a canonical latency or throughput metric")


def _child(root: Path, value: str) -> Path:
    if not isinstance(value, str) or not value or "\\" in value:
        raise ValueError("references must be non-empty portable relative paths")
    relative = Path(value)
    if relative.is_absolute() or ".." in relative.parts or ":" in value:
        raise ValueError("references must stay within the declared root")
    path = (root / relative).resolve()
    if not path.is_relative_to(root):
        raise ValueError("reference escapes the declared root")
    return path


def _read(path: Path) -> tuple[dict, str]:
    with path.open("rb") as handle:
        data = handle.read(MAX_BYTES + 1)
    if len(data) > MAX_BYTES:
        raise ValueError("catalog or artifact exceeds the 8 MiB read limit")
    document = json.loads(data)
    if not isinstance(document, dict):
        raise ValueError("catalog and artifacts must be JSON objects")
    return document, hashlib.sha256(data).hexdigest()


def _text(value, field: str) -> str:
    if not isinstance(value, str) or not value.strip() or len(value) > 2000 or any(ord(c) < 32 for c in value):
        raise ValueError(f"{field} must be non-empty text of at most 2000 characters")
    return value


def _texts(value, field: str) -> list[str]:
    if not isinstance(value, list) or not 1 <= len(value) <= 12:
        raise ValueError(f"{field} must contain 1..12 text items")
    return [_text(item, field) for item in value]


def _number(value, field: str):
    if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value):
        raise ValueError(f"{field} must be finite numeric evidence")
    return value


def _metric(raw: dict, path: str):
    if not isinstance(path, str) or not re.fullmatch(r"metrics\.[a-zA-Z0-9_.]+", path):
        raise ValueError("metric references must name a metrics field")
    value = raw
    for key in path.split("."):
        if not isinstance(value, dict) or key not in value:
            raise ValueError(f"metric not recorded: {path}")
        value = value[key]
    value = _number(value, path)
    if value < 0:
        raise ValueError("performance metrics cannot be negative")
    return value


def _validate_distributions(metrics: dict) -> None:
    for family, suffix in (("ttft", "_ms"), ("e2e", "_ms"), ("tpot", "_ms"),
                           ("decode_tok_s", ""), ("effective_prefill_tok_s", ""),
                           ("prompt_tokens", ""), ("completion_tokens", "")):
        values = []
        for stat in ("min", "p25", "p50", "p75", "p90", "p95", "p99", "max"):
            key = f"{family}_{stat}{suffix}"
            value = metrics.get(key)
            if value is not None:
                value = _number(value, key)
                if value < 0:
                    raise ValueError("distributions cannot contain negative values")
                values.append(value)
        if values != sorted(values):
            raise ValueError("distribution quantiles must be monotonic")
        mean = metrics.get(f"{family}_mean{suffix}")
        if mean is not None:
            mean = _number(mean, family)
            lower = metrics.get(f"{family}_min{suffix}", 0)
            upper = metrics.get(f"{family}_max{suffix}")
            if mean < (lower if lower is not None else 0) or (upper is not None and mean > upper):
                raise ValueError("distribution mean must stay within its recorded range")


def build_report(catalog: Path, root: Path) -> dict:
    """Resolve a bounded catalog once per artifact; never read prompts into the report."""
    root = root.resolve()
    catalog = catalog.resolve()
    if not catalog.is_relative_to(root):
        raise ValueError("catalog must stay within the declared root")
    document, digest = _read(catalog)
    if document.get("schema") != SCHEMA:
        raise ValueError(f"catalog schema must be {SCHEMA}")
    entries = document.get("entries")
    if not isinstance(entries, list) or not 1 <= len(entries) <= 128:
        raise ValueError("catalog must contain 1..128 entries")
    report = {
        "schema": REPORT_SCHEMA,
        "title": _text(document.get("title"), "title"),
        "reviewed_at": _text(document.get("reviewed_at"), "reviewed_at"),
        "catalog": catalog.relative_to(root).as_posix(),
        "catalog_sha256": digest,
        "source_base_url": _text(document.get("source_base_url"), "source_base_url"),
        "entries": [],
    }
    source_url = urlsplit(report["source_base_url"])
    if source_url.scheme != "https" or not source_url.hostname or source_url.username or source_url.password or source_url.query or source_url.fragment:
        raise ValueError("source_base_url must be an HTTPS source URL without credentials, query, or fragment")
    if not re.fullmatch(r"/[A-Za-z0-9_./-]+/[0-9a-f]{40}/", source_url.path):
        raise ValueError("source_base_url must end in an immutable 40-character source revision and slash")
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", report["reviewed_at"]):
        raise ValueError("reviewed_at must be YYYY-MM-DD")
    cache = {}
    seen = set()
    for entry in entries:
        if not isinstance(entry, dict):
            raise ValueError("each catalog entry must be an object")
        identifier = entry.get("id")
        if not isinstance(identifier, str) or not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", identifier) or identifier in seen:
            raise ValueError("entry IDs must be unique lowercase slugs")
        seen.add(identifier)
        row = {key: _text(entry.get(key), key) for key in ("title", "model", "hardware", "topology", "workload")}
        row.update(id=identifier, decision=entry.get("decision"))
        if row["decision"] not in DECISIONS:
            raise ValueError("entry has an unknown evidence decision")
        for field in ("strengths", "limitations"):
            row[field] = _texts(entry.get(field), field)
        for field in ("recipe", "finding", "dossier"):
            link = entry.get(field)
            if not isinstance(link, dict):
                raise ValueError(f"{field} must supply a path and label")
            path = _child(root, link.get("path"))
            if not path.is_file():
                raise ValueError(f"missing {field} reference")
            row[field] = {"path": path.relative_to(root).as_posix(), "label": _text(link.get("label"), field)}
            if field == "recipe":
                with path.open("rb") as handle:
                    recipe_bytes = handle.read(MAX_BYTES + 1)
                if len(recipe_bytes) > MAX_BYTES:
                    raise ValueError("recipe exceeds read limit")
                recipes = tomllib.loads(recipe_bytes.decode("utf-8")).get("recipe", [])
                selector = link.get("selector")
                if not isinstance(recipes, list) or not recipes:
                    raise ValueError("recipe file must contain a recipe array")
                selected = [item for item in recipes if isinstance(item, dict) and (item.get("model") == selector or (selector is None and len(recipes) == 1))]
                if len(selected) != 1:
                    raise ValueError("multi-recipe files require one exact selector")
                row[field]["selector"] = _text(selected[0].get("model"), "recipe selector")
                row[field]["sha256"] = hashlib.sha256(recipe_bytes).hexdigest()
        artifact = _child(root, entry.get("artifact"))
        if artifact not in cache:
            cache[artifact] = _read(artifact)
        raw, artifact_hash = cache[artifact]
        if raw.get("schema") != "anvil-serving.benchmark/v1":
            raise ValueError("recipe metrics require native capacity evidence")
        expected = entry.get("expected")
        if not isinstance(expected, dict) or set(expected) != set(IDENTITY_FIELDS):
            raise ValueError("entry expected identity must declare every native identity/workload field")
        for key in IDENTITY_FIELDS:
            if (key not in raw and key not in LEGACY_OPTIONAL_FIELDS) or type(expected[key]) is not type(raw.get(key)) or expected[key] != raw.get(key):
                raise ValueError(f"artifact identity/workload mismatch: {key}")
        row["native_identity"] = {key: _text(raw.get(key), key) for key in ("model", "engine", "gpu", "measurement_protocol")}
        recipe = selected[0]
        serve = recipe.get("serve", {})
        if not isinstance(serve, dict):
            raise ValueError("recipe serve must be a table")
        recipe_engine = _text(serve.get("engine"), "recipe engine")
        engine_matches = raw["engine"] == recipe_engine or re.fullmatch(re.escape(recipe_engine) + r"-\d+\.\d+\.\d+(?:[a-zA-Z0-9.+-]*)", raw["engine"])
        if serve.get("served_model_name") != raw["model"] or not engine_matches:
            raise ValueError("selected recipe served identity does not match native artifact")
        if raw.get("max_context_tokens") is not None and serve.get("context_tokens") != raw["max_context_tokens"]:
            raise ValueError("selected recipe context does not match native artifact")
        # Editorial copy cannot override the authoritative measured identity.
        row["model"] = raw["model"]
        row["hardware"] = raw["gpu"]
        row["workload"] = (f"Prompt target {raw['context_tokens']} tokens; C{raw['concurrency']}; "
                           f"{raw.get('requests')} requests; {raw['prompt_cache_mode']} cache; "
                           f"request canaries={raw['request_canaries']}.")
        row["topology"] = "Catalog topology annotation: " + row["topology"]
        row["artifact"] = artifact.relative_to(root).as_posix()
        row["artifact_sha256"] = artifact_hash
        row["conditions"] = {key: raw.get(key) for key in (
            "requests", "completed", "failed", "concurrency", "context_tokens", "max_context_tokens",
            "max_tokens", "response_words", "controlled_output_policy", "shared_prefix_tokens", "prompt_cache_mode", "request_canaries", "measurement_protocol",
        )}
        for key in ("requests", "completed", "failed", "concurrency"):
            value = _number(row["conditions"][key], key)
            if type(value) is not int or value < 0:
                raise ValueError(f"{key} must be a nonnegative integer")
        c = row["conditions"]
        if c["requests"] < 1 or c["concurrency"] < 1 or c["completed"] + c["failed"] != c["requests"]:
            raise ValueError("request population must reconcile completed + failed = requested")
        for key in ("context_tokens", "max_context_tokens", "max_tokens", "response_words", "shared_prefix_tokens"):
            value = c[key]
            if value is not None and (type(value) is not int or value < 0):
                raise ValueError(f"{key} must be a nonnegative integer or null")
        if c["context_tokens"] and c["max_context_tokens"] and c["context_tokens"] > c["max_context_tokens"]:
            raise ValueError("context target exceeds configured context")
        if c["controlled_output_policy"] not in {"observe", "strict", None}:
            raise ValueError("invalid controlled output policy")
        if c["prompt_cache_mode"] not in {"unique", "shared", None} or (c["request_canaries"] is not None and type(c["request_canaries"]) is not bool):
            raise ValueError("invalid cache or canary condition")
        flags = raw.get("serve_flags", {})
        if not isinstance(flags, dict):
            raise ValueError("serve_flags must be an object")
        row["conditions"]["thinking_mode"] = flags.get("thinking_mode", "not recorded")
        row["conditions"]["performance_eligible"] = raw.get("performance_eligible")
        if raw.get("performance_eligible") is not None and type(raw["performance_eligible"]) is not bool:
            raise ValueError("performance_eligible must be boolean or null")
        row["conditions"]["timing_precision"] = raw.get("timing_precision", raw.get("timeline_precision"))
        for key, value in row["conditions"].items():
            if value is not None and not isinstance(value, (str, int, float, bool)):
                raise ValueError(f"{key} must be a scalar condition")
            if isinstance(value, str) and len(value) > 100:
                raise ValueError(f"{key} exceeds the condition text limit")
        native_metrics = raw.get("metrics", {})
        if not isinstance(native_metrics, dict):
            raise ValueError("metrics must be an object")
        _validate_distributions(native_metrics)
        row["token_counts"] = {key: native_metrics.get(key) for key in (
            "prompt_tokens_min", "prompt_tokens_p50", "prompt_tokens_max",
            "completion_tokens_min", "completion_tokens_mean", "completion_tokens_max",
        )}
        for key, value in row["token_counts"].items():
            if value is not None:
                _number(value, key)
                if value < 0:
                    raise ValueError("token counts cannot be negative")
        row["metrics"] = []
        metrics = entry.get("metrics")
        if not isinstance(metrics, list) or not 1 <= len(metrics) <= 12:
            raise ValueError("entry must select 1..12 metrics")
        for metric in metrics:
            if not isinstance(metric, dict):
                raise ValueError("metric must be an object")
            precision = metric.get("precision", 1)
            if type(precision) is not int or not 0 <= precision <= 4:
                raise ValueError("metric precision must be 0..4")
            label, unit = _metric_contract(metric.get("path"))
            if metric.get("unit") != unit:
                raise ValueError("metric unit does not match its native field")
            row["metrics"].append({
                "label": label,
                "path": metric.get("path"),
                "value": _metric(raw, metric.get("path")),
                "unit": unit,
                "precision": precision,
            })
        report["entries"].append(row)
    return report


def render_markdown(report: dict, output: Path, root: Path) -> str:
    """Render accessible static cards with all numeric values sourced from artifacts."""
    def esc(value):
        return html.escape(str(value), quote=True)

    def href(path):
        target = root / path
        if path.startswith("docs/"):
            return quote(os.path.relpath(target, output.parent).replace("\\", "/"), safe="/.-_")
        return report["source_base_url"].rstrip("/") + "/" + quote(path, safe="/.-_")

    title = esc(report['title']).replace('[', '&#91;').replace(']', '&#93;')
    lines = [f"# {title}", "", MARKER, "",
             "Choose by hardware and workload, then inspect the recipe and its limits. These are published evidence decisions; each result applies to its recorded configuration.", "",
             f"Reviewed {esc(report['reviewed_at'])}. [Comparison history](comparison.md) · [Container reconstruction](configurations.md) · [Measurement definitions](methodology.md).", "",
             "<details><summary>How to compare these measurements</summary><p>Request percentiles describe this sample, including at n=100; they do not establish stable production tails. TPOT and mean ITL in capacity-v3 are the same per-request average, not token-arrival intervals. Effective prefill includes queueing and first-output work. Compare only matched workload and configuration populations.</p></details>", "",
             '<div class="bench-recipes" markdown="1">', '']
    for row in report["entries"]:
        c = row["conditions"]
        lines += ['<article class="bench-recipe" markdown="1">', '',
                  f'<p class="bench-recipe__eyebrow">{esc(row["hardware"])} · {esc(row["topology"])}</p>',
                  f'<h2 class="bench-recipe__title" id="{esc(row["id"])}">{esc(row["title"])}</h2>',
                  f'<p><span class="bench-status--{esc(row["decision"])}">{esc(row["decision"])}</span> · {esc(row["model"])}</p>',
                  f'<p>{esc(row["workload"])}</p>',
                  '<dl class="bench-recipe__metrics">']
        for metric in row["metrics"]:
            value = f"{metric['value']:,.{metric['precision']}f}"
            lines.append(f'<div class="bench-recipe__metric"><dt>{esc(metric["label"])}</dt><dd>{value} {esc(metric["unit"])}</dd></div>')
        lines += ['</dl>', '<p class="bench-recipe__meta">' + esc(
            f"n={c['completed']}/{c['requests']}; failed={c['failed']}; C{c['concurrency']}; "
            f"prompt target={c['context_tokens']}; configured context={c['max_context_tokens']}; "
            f"output cap={c['max_tokens']}; response word target={c['response_words']}; "
            f"output policy={c['controlled_output_policy'] or 'not recorded (legacy)'}; "
            f"shared prefix target={c['shared_prefix_tokens'] if c['shared_prefix_tokens'] is not None else 'not recorded'}; "
            f"cache={c['prompt_cache_mode']}; thinking={c['thinking_mode']}."
        ) + '</p>']
        tokens = row["token_counts"]
        def recorded(key):
            return "not recorded" if tokens[key] is None else f"{tokens[key]:,.1f}"
        lines.append('<p class="bench-recipe__meta">' + esc(
            f"Actual prompt tokens min/P50/max: {recorded('prompt_tokens_min')} / {recorded('prompt_tokens_p50')} / {recorded('prompt_tokens_max')}. "
            f"Actual completion tokens min/mean/max: {recorded('completion_tokens_min')} / {recorded('completion_tokens_mean')} / {recorded('completion_tokens_max')}."
        ) + '</p>')
        if c["completed"] < c["requests"] or c["failed"] or c["performance_eligible"] is False:
            lines.append('<p><strong>Incomplete or failed population: performance is diagnostic only.</strong></p>')
        for field, label in (("strengths", "Strengths"), ("limitations", "Limits and untested work")):
            lines.append(f'<div class="bench-recipe__{field}"><h3>{label}</h3><ul>')
            lines.extend(f'<li>{esc(value)}</li>' for value in row[field])
            lines.append('</ul></div>')
        lines += ['', '<div class="bench-recipe__actions" markdown="1">', '']
        def link_label(value):
            return esc(value).replace('[', '&#91;').replace(']', '&#93;')
        links = [f'[{link_label(row[field]["label"])}]({href(row[field]["path"])})' for field in ("recipe", "finding", "dossier")]
        links.append(f'[Raw measurements]({href(row["artifact"])})')
        provenance = (
            '<details><summary>Evidence provenance</summary>'
            f'<p>Source SHA-256: <code>{row["artifact_sha256"]}</code>. '
            'Metric values are generated from the linked native artifact. Recipe selection '
            'and strengths/limits are reviewed catalog annotations.</p>'
            f'<p>Recipe selector: <code>{esc(row["recipe"]["selector"])}</code>. '
            f'Recipe SHA-256: <code>{row["recipe"]["sha256"]}</code>.</p>'
            '<p>Native identity: ' + esc('; '.join(f'{key}={value}' for key, value in row['native_identity'].items()))
            + '</p></details>'
        )
        lines += [' '.join(links), '', '</div>', '', provenance, '', '</article>', '']
    lines += ['</div>', '', f'Catalog SHA-256: `{report["catalog_sha256"]}`.', '']
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, prog="anvil-serving eval benchmark report")
    parser.add_argument("catalog", type=Path)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--format", choices=("markdown", "json"), default="markdown")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check", action="store_true", help="Verify the existing output byte-for-byte without writing.")
    parser.add_argument("--confirm", action="store_true", help="Authorize replacing the named generated report.")
    args = parser.parse_args(argv)
    try:
        root = args.root.resolve()
        output = args.output.resolve() if args.output else root / "docs/benchmarks/recipe-results.md"
        if not output.is_relative_to(root):
            raise ValueError("report output must stay within the declared root")
        report = build_report(args.catalog, root)
        inputs = {report["catalog"]} | {row[key] for row in report["entries"] for key in ("artifact",)} | {row[key]["path"] for row in report["entries"] for key in ("recipe", "finding", "dossier")}
        if output.relative_to(root).as_posix() in inputs:
            raise ValueError("report output cannot replace a source input")
        content = (json.dumps(report, indent=2, ensure_ascii=True, allow_nan=False) + "\n") if args.format == "json" else render_markdown(report, output, root)
        if args.check:
            if not args.output:
                raise ValueError("--check requires --output")
            if output.read_bytes() != content.encode("utf-8"):
                raise ValueError("generated report is stale; regenerate from the reviewed catalog")
            print(f"report current: {len(report['entries'])} recipes")
        elif args.output:
            if not args.confirm:
                raise ValueError("--output requires --confirm; use --check for read-only verification")
            if output.suffix != (".json" if args.format == "json" else ".md"):
                raise ValueError("generated report must use the matching .md or .json extension")
            prior_mode = None
            if output.exists():
                prior_mode = output.stat().st_mode
                if args.format == "json":
                    if _read(output)[0].get("schema") != REPORT_SCHEMA:
                        raise ValueError("refusing to replace a file that is not a generated recipe report")
                elif MARKER not in output.read_text(encoding="utf-8")[:1000]:
                    raise ValueError("refusing to replace a file that is not a generated recipe report")
            temporary = None
            try:
                with tempfile.NamedTemporaryFile(dir=output.parent, delete=False) as handle:
                    temporary = Path(handle.name)
                    handle.write(content.encode("utf-8"))
                if prior_mode is not None:
                    os.chmod(temporary, prior_mode)
                os.replace(temporary, output)
            finally:
                if temporary is not None:
                    temporary.unlink(missing_ok=True)
            print(f"wrote report: {len(report['entries'])} recipes")
        else:
            print(content, end="")
        return 0
    except (OSError, ValueError, TypeError, KeyError) as exc:
        print(f"benchmark report: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
