"""Bounded, metadata-only audit records for direct gateway requests.

Records contain route and tier identifiers, outcome labels, token counts,
correlation identifiers, and byte/latency measurements. They never contain
prompts, responses, audio, transcripts, synthesis text, or credentials.
"""
from __future__ import annotations

import dataclasses
import json
import os
import re
import sys
import threading
import time
from collections import Counter, deque
from dataclasses import dataclass, field
from datetime import datetime
from itertools import islice
from typing import Any, Callable, Deque, Iterable, Mapping, Optional, Tuple

from .replica_scheduler import (
    PressureFreshness,
    ReplicaDecision,
    ReplicaDecisionReason,
    ReplicaScore,
)

#: Default ring-buffer capacity for :class:`DecisionLog`. One record per routed
#: request; 10k bounds a long-running server's audit memory to the recent
#: window while staying far above what an operator inspects interactively.
DEFAULT_MAX_RECORDS = 10_000
_SUMMARY_SECRET_RE = re.compile(
    r"(?i)(bearer_[A-Za-z0-9._~+/\-]{6,}|bearer\s+[A-Za-z0-9._~+/\-]{6,}|"
    r"sk-(?:proj-)?[A-Za-z0-9_-]{6,}|"
    r"[A-Z0-9_-]*(?:TOKEN|SECRET|API_KEY|API-KEY|KEY)[A-Z0-9_-]*\s*[:=]\s*[^\s]+)"
)
_CORRELATION_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$")
_GATEWAY_REQUEST_ID_RE = re.compile(r"^req_[0-9a-f]{32}$")
_WORKLOAD_TIMESTAMP_RE = re.compile(
    r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{6}Z$"
)
_WORKLOAD_OUTCOMES = {
    "success", "error", "cancelled", "timeout", "rejected", "disconnected",
}
_MAX_MEASUREMENT = 1_000_000_000_000_000
_REPLICA_MEMBER_RE = re.compile(r"[A-Za-z][A-Za-z0-9_-]{0,63}")


@dataclass(frozen=True)
class AttemptRecord:
    """One direct tier attempt with content-free outcome metadata."""

    tier_id: str
    succeeded: bool
    reason: str
    prompt_tokens: int
    completion_tokens: int
    outcome: str


@dataclass(frozen=True)
class DecisionRecord:
    """The metadata-only audit record for one direct request."""

    kind: Optional[str]
    requested_tier: str
    attempts: Tuple[AttemptRecord, ...]
    served_tier: Optional[str]
    total_prompt_tokens: int
    total_completion_tokens: int
    route: Optional[str] = None
    # Workbench lineage metadata. These identifiers are supplied by a trusted
    # private harness header and sanitized at the front door; they are never
    # prompt/response content and remain optional for all existing callers.
    request_id: Optional[str] = None
    # Generated by the gateway, never caller-controlled. It is authoritative
    # for one-record lookup and is the only correlation id allowed in lines.
    gateway_request_id: Optional[str] = None
    workbench_run_id: Optional[str] = None
    task_id: Optional[str] = None
    # Content-free transport metadata for binary/purpose gateways.  Audio uses
    # these fields to expose hop volume and elapsed time without retaining the
    # audio payload, base64, transcript, or synthesis input.  They default to
    # zero so existing chat decisions remain byte-for-byte compatible.
    request_bytes: int = 0
    response_bytes: int = 0
    latency_ms: int = 0
    # Terminal chat measurements are deliberately scalar and content-free.
    # ``None`` means the router could not observe that phase; zero is retained
    # only when a phase was actually measured below one millisecond.
    readiness_check_ms: Optional[int] = None
    upstream_duration_ms: Optional[int] = None
    # This measures first nonempty emitted *content delta*. Tool-only streams
    # intentionally leave it absent: it is not a universal TTFT claim.
    time_to_first_content_ms: Optional[int] = field(default=None, repr=False)
    # Normalized from a small allowlist. Raw provider finish strings never
    # enter this public/operator-visible record.
    finish_reason: Optional[str] = None
    # Per-field provenance makes partial upstream accounting honest. Existing
    # numeric token fields keep their historical aggregate semantics.
    prompt_tokens_source: Optional[str] = None
    completion_tokens_source: Optional[str] = None
    # Effective output ceiling after the router's bounded tier clamp. The
    # client request can be absent; unknown fields remain ``None``.
    output_limit_requested: Optional[int] = None
    output_limit_applied: Optional[int] = None
    output_limit_clamped: Optional[bool] = None
    # ADR-0033: wall-clock creation stamp for durable evidence. Stamped by
    # :meth:`DecisionLog.record` when left at the zero default; aggregate views
    # remain snapshots of the buffer, never historical windows.
    unix_ts: float = 0.0
    # Workload visibility adds only canonical timestamps and a fixed outcome.
    # They remain absent for ordinary callers, preserving legacy projections.
    workload_created_at: Optional[str] = field(default=None, repr=False)
    workload_updated_at: Optional[str] = field(default=None, repr=False)
    workload_outcome: Optional[str] = field(default=None, repr=False)
    # Selection identifies a configured member, not successful generation.
    replica_member_id: Optional[str] = None
    replica_selection: Optional[str] = None
    # A copied capacity-ordering observation captured before admission reserves
    # the selected member.  It is absent for direct and round-robin routes.
    replica_scheduler: Optional[ReplicaDecision] = None


def safe_correlation(value: Any) -> Optional[str]:
    """Accept a compact opaque correlation identifier or discard it.

    Decision logs are operator-visible and sometimes exported as line-oriented
    evidence, so caller-controlled values cannot carry whitespace, control
    characters, or arbitrary content. The router treats malformed correlation
    headers as absent rather than failing an otherwise valid model request.
    """
    candidate = str(value or "")
    return candidate if _CORRELATION_RE.fullmatch(candidate) else None


def request_correlation(request: Any) -> dict[str, Optional[str]]:
    """Read the front-door-stamped Workbench lineage from an internal request."""
    raw = getattr(request, "raw", {})
    source = raw.get("_anvil_correlation", {}) if isinstance(raw, Mapping) else {}
    if not isinstance(source, Mapping):
        source = {}
    return {
        "request_id": safe_correlation(source.get("request_id")),
        "gateway_request_id": safe_gateway_request_id(source.get("gateway_request_id")),
        "workbench_run_id": safe_correlation(source.get("workbench_run_id")),
        "task_id": safe_correlation(source.get("task_id")),
    }


def _safe(token: Optional[str]) -> str:
    """Render a string field safely for the single-line ``label=value`` grammar.

    Collapses any whitespace/newline run and the ``>`` tier separator to ``_``.
    This is load-bearing because ``intent`` can be caller-derived (the raw wire
    ``model`` string): without it, a ``model`` carrying a newline
    would inject a forged second audit line (log injection), and any embedded
    space would break ``key=value`` parsing. Operator-set tier ids and kinds
    get the same guarantee. ``None``/empty render as ``-``.
    """
    if not token:
        return "-"
    return re.sub(r"[\s>]+", "_", str(token))


def safe_gateway_request_id(value: Any) -> Optional[str]:
    """Accept only the gateway's fixed, generated request-id shape."""
    candidate = str(value or "")
    return candidate if _GATEWAY_REQUEST_ID_RE.fullmatch(candidate) else None


def _summary_safe(token: Optional[str]) -> str:
    if not token:
        return "-"
    placeholder = "__ANVIL_REDACTED__"
    safe = _safe(_SUMMARY_SECRET_RE.sub(placeholder, str(token)))
    return safe.replace(placeholder, "<redacted>")


def decision_line(record: DecisionRecord) -> str:
    """A single content-FREE audit line carrying every AC2 field.

    Shape::

        route=<i|-> kind=<wc|-> served=<tier|-> outcome=<served|failed> \
tier=<t|-> prompt=<n> completion=<n>

    ``verify`` is ``pass`` when a tier served (``served_tier`` is set) else
    ``fail``; ``-`` stands in for a missing/empty route/kind/served/tier.
    Every string field is passed
    through :func:`_safe` so the line is ALWAYS a single, parseable sequence of
    ``label=value`` tokens regardless of caller- or operator-supplied content.
    Only labels and integers — never message text or a verifier's raw reason (R012).
    """
    served = record.served_tier
    line = (
        f"route={_safe(record.route)} "
        f"kind={_safe(record.kind)} "
        f"served={_safe(served)} "
        f"outcome={'served' if served is not None else 'failed'} "
        f"tier={_safe(record.requested_tier)} "
        f"prompt={record.total_prompt_tokens} "
        f"completion={record.total_completion_tokens}"
    )
    # Preserve the established eight-field chat audit grammar.  Binary gateway
    # records add only content-free measurements, satisfying observability
    # without putting raw audio or transcript text into container logs.
    request_bytes = max(_int_field(record, "request_bytes"), 0)
    response_bytes = max(_int_field(record, "response_bytes"), 0)
    latency_ms = max(_int_field(record, "latency_ms"), 0)
    if request_bytes or response_bytes or latency_ms:
        line += (
            f" request_bytes={request_bytes}"
            f" response_bytes={response_bytes}"
            f" latency_ms={latency_ms}"
        )
    gateway_request_id = safe_gateway_request_id(record.gateway_request_id)
    if gateway_request_id is not None:
        line += f" gateway_request_id={gateway_request_id}"
    for name, value in _replica_metadata(record).items():
        line += f" {name}={value}"
    scheduler = _replica_scheduler_metadata(record)
    if scheduler is not None:
        line += (
            " replica_scheduler=capacity"
            " replica_scheduler_reason=selected"
            f" replica_eligible_count={len(scheduler['eligible_member_ids'])}"
        )
    return line


def _field(record: Any, name: str, default: Any = None) -> Any:
    if isinstance(record, Mapping):
        return record.get(name, default)
    return getattr(record, name, default)


def _replica_metadata(record: Any) -> dict[str, str]:
    """Bounded optional pair projection shared by every audit surface."""
    member = _field(record, "replica_member_id")
    selection = _field(record, "replica_selection")
    if type(selection) is not str or len(selection) > 16:
        return {}
    if selection == "identity_passed":
        if (
            type(member) is str
            and 1 <= len(member) <= 64
            and _REPLICA_MEMBER_RE.fullmatch(member) is not None
        ):
            return {"replica_member_id": member, "replica_selection": selection}
    elif selection in {"not_admitted", "request_rejected"} and member is None:
        return {"replica_selection": selection}
    return {}


def _sanitize_replica_metadata(record: DecisionRecord) -> DecisionRecord:
    if record.replica_member_id is None and record.replica_selection is None:
        return record
    if _replica_metadata(record):
        return record
    return dataclasses.replace(record, replica_member_id=None, replica_selection=None)


def _copy_replica_scheduler(value: object) -> Optional[ReplicaDecision]:
    """Detach one exact typed scheduler observation or drop it safely."""
    if type(value) is not ReplicaDecision:
        return None
    try:
        if type(value.eligible_member_ids) is not tuple or type(value.scores) is not tuple:
            return None
        if len(value.eligible_member_ids) > 16 or len(value.scores) > 16:
            return None
        copied_scores = []
        for score in value.scores:
            if type(score) is not ReplicaScore:
                return None
            copied_scores.append(ReplicaScore(
                score.member_id, score.local_numerator, score.local_denominator,
                score.upstream_unknown, score.upstream_pressure_ppm,
                score.rotating_rank, score.freshness,
            ))
        return ReplicaDecision(
            value.selected_member_id, tuple(value.eligible_member_ids),
            tuple(copied_scores), value.reason,
        )
    except (AttributeError, TypeError, ValueError):
        return None


def validated_replica_scheduler(
    value: object,
    *,
    selected_member_id: object,
    member_capacities: Mapping[str, int],
) -> Optional[ReplicaDecision]:
    """Return detached capacity evidence only when it fits this configured tier."""
    copied = _copy_replica_scheduler(value)
    if copied is None or type(selected_member_id) is not str:
        return None
    if copied.reason is not ReplicaDecisionReason.SELECTED:
        return None
    if copied.selected_member_id != selected_member_id:
        return None
    try:
        if set(copied.eligible_member_ids) != {score.member_id for score in copied.scores}:
            return None
        for score in copied.scores:
            ceiling = member_capacities.get(score.member_id)
            if type(ceiling) is not int:
                return None
            if score.local_denominator != ceiling or score.local_numerator >= ceiling:
                return None
    except (AttributeError, TypeError, ValueError):
        return None
    return copied


def _scheduler_from_mapping(value: object) -> Optional[ReplicaDecision]:
    """Reconstruct a closed captured JSON projection without retaining mappings."""
    if type(value) is not dict or set(value) != {
        "selected_member_id", "eligible_member_ids", "scores", "reason",
    }:
        return None
    selected = value["selected_member_id"]
    eligible = value["eligible_member_ids"]
    scores = value["scores"]
    reason = value["reason"]
    if type(selected) is not str or type(eligible) is not list or type(scores) is not list:
        return None
    if type(reason) is not str or len(eligible) > 16 or len(scores) > 16:
        return None
    if any(type(member) is not str for member in eligible):
        return None
    copied_scores = []
    score_keys = {
        "member_id", "local_numerator", "local_denominator", "upstream_unknown",
        "upstream_pressure_ppm", "rotating_rank", "freshness",
    }
    try:
        for raw_score in scores:
            if type(raw_score) is not dict or set(raw_score) != score_keys:
                return None
            freshness = raw_score["freshness"]
            if type(freshness) is not str:
                return None
            copied_scores.append(ReplicaScore(
                raw_score["member_id"], raw_score["local_numerator"],
                raw_score["local_denominator"], raw_score["upstream_unknown"],
                raw_score["upstream_pressure_ppm"], raw_score["rotating_rank"],
                PressureFreshness(freshness),
            ))
        return ReplicaDecision(
            selected, tuple(eligible), tuple(copied_scores),
            ReplicaDecisionReason(reason),
        )
    except (KeyError, TypeError, ValueError):
        return None


def _replica_scheduler_metadata(record: object) -> Optional[dict]:
    """Return the sole safe scheduler projection for lines, summaries and JSONL."""
    value = _field(record, "replica_scheduler")
    copied = _copy_replica_scheduler(value)
    if copied is None and isinstance(record, Mapping):
        copied = _scheduler_from_mapping(value)
    return copied.to_dict() if copied is not None else None


def _sanitize_replica_scheduler(record: DecisionRecord) -> DecisionRecord:
    copied = _copy_replica_scheduler(record.replica_scheduler)
    if copied is record.replica_scheduler:
        return record
    return dataclasses.replace(record, replica_scheduler=copied)


def _int_field(record: Any, name: str) -> int:
    value = _field(record, name, 0)
    if isinstance(value, bool):
        return 0
    try:
        return int(value)
    except (TypeError, ValueError):
        return 0


def _optional_nonnegative(value: Any) -> Optional[int]:
    """Return a real nonnegative scalar, preserving an unknown as ``None``."""
    if isinstance(value, bool) or not isinstance(value, int):
        return None
    return value if 0 <= value <= _MAX_MEASUREMENT else None


def _optional_bool(value: Any) -> Optional[bool]:
    return value if isinstance(value, bool) else None


def _token_source(value: Any) -> Optional[str]:
    """Project only the three accounting provenance states."""
    return value if isinstance(value, str) and value in {"upstream", "estimated", "unknown"} else None


def _finish_reason(value: Any) -> Optional[str]:
    """Project only router-normalized terminal reasons, never provider text."""
    return value if isinstance(value, str) and value in {"stop", "length", "tool_calls", "content_filter"} else None


def _attempt_summary(attempt: Any) -> dict:
    return {
        "tier_id": _summary_safe(_field(attempt, "tier_id")),
        "outcome": _summary_safe(_field(attempt, "outcome")),
        "succeeded": bool(_field(attempt, "succeeded", False)),
        "reason": _summary_safe(_field(attempt, "reason")),
        "prompt_tokens": _int_field(attempt, "prompt_tokens"),
        "completion_tokens": _int_field(attempt, "completion_tokens"),
    }


def summarize_decisions(records: Iterable[Any], *, limit: int = 20) -> dict:
    """Summarize recent routing decisions without prompt, response, or secret text.

    Accepts real :class:`DecisionRecord` objects or JSON-like mappings from a
    captured metadata artifact. Unknown fields are ignored deliberately; the
    output is the safe audit projection only.
    """
    if limit <= 0:
        raise ValueError("limit must be positive")
    all_records = list(records)
    selected = all_records[-limit:]
    items = []
    served_counts: Counter[str] = Counter()
    outcome_counts: Counter[str] = Counter()
    total_prompt = 0
    total_completion = 0
    total_request_bytes = 0
    total_response_bytes = 0
    total_latency_ms = 0
    for record in selected:
        attempts = tuple(_field(record, "attempts", ()) or ())
        attempt_items = [_attempt_summary(attempt) for attempt in attempts]
        served = _summary_safe(_field(record, "served_tier"))
        prompt_tokens = _int_field(record, "total_prompt_tokens")
        completion_tokens = _int_field(record, "total_completion_tokens")
        request_bytes = max(_int_field(record, "request_bytes"), 0)
        response_bytes = max(_int_field(record, "response_bytes"), 0)
        latency_ms = max(_int_field(record, "latency_ms"), 0)
        if served != "-":
            served_counts[served] += 1
        for attempt in attempt_items:
            outcome_counts[attempt["outcome"]] += 1
        total_prompt += prompt_tokens
        total_completion += completion_tokens
        total_request_bytes += request_bytes
        total_response_bytes += response_bytes
        total_latency_ms += latency_ms
        item = {
            "route": _summary_safe(_field(record, "route")),
            "kind": _summary_safe(_field(record, "kind")),
            "requested_tier": _summary_safe(_field(record, "requested_tier")),
            "served_tier": served,
            "attempts": attempt_items,
            "total_prompt_tokens": prompt_tokens,
            "total_completion_tokens": completion_tokens,
            "request_bytes": request_bytes,
            "response_bytes": response_bytes,
            "latency_ms": latency_ms,
            "measurements": {
                "readiness_check_ms": _optional_nonnegative(
                    _field(record, "readiness_check_ms")
                ),
                "upstream_duration_ms": _optional_nonnegative(
                    _field(record, "upstream_duration_ms")
                ),
                "time_to_first_content_ms": _optional_nonnegative(
                    _field(record, "time_to_first_content_ms")
                ),
                "finish_reason": _finish_reason(_field(record, "finish_reason")),
            },
            "usage": {
                "prompt_tokens": prompt_tokens,
                "completion_tokens": completion_tokens,
                "prompt_source": _token_source(
                    _field(record, "prompt_tokens_source")
                ),
                "completion_source": _token_source(
                    _field(record, "completion_tokens_source")
                ),
            },
            "output_limit": {
                "requested": _optional_nonnegative(
                    _field(record, "output_limit_requested")
                ),
                "applied": _optional_nonnegative(
                    _field(record, "output_limit_applied")
                ),
                "clamped": _optional_bool(_field(record, "output_limit_clamped")),
            },
            "request_id": _summary_safe(safe_correlation(_field(record, "request_id"))),
            "gateway_request_id": _summary_safe(
                safe_gateway_request_id(_field(record, "gateway_request_id"))
            ),
            "workbench_run_id": _summary_safe(safe_correlation(_field(record, "workbench_run_id"))),
            "task_id": _summary_safe(safe_correlation(_field(record, "task_id"))),
            **_replica_metadata(record),
        }
        scheduler = _replica_scheduler_metadata(record)
        if scheduler is not None:
            item["replica_scheduler"] = scheduler
        items.append(item)
    return {
        "count": len(items),
        "available": len(all_records),
        "limit": limit,
        "records": items,
        "totals": {
            "prompt_tokens": total_prompt,
            "completion_tokens": total_completion,
            "request_bytes": total_request_bytes,
            "response_bytes": total_response_bytes,
            "latency_ms": total_latency_ms,
            "served_tiers": dict(sorted(served_counts.items())),
            "attempt_outcomes": dict(sorted(outcome_counts.items())),
        },
        "omitted_fields": [
            "prompt", "messages", "content", "response", "api_key",
            "authorization", "token", "audio", "audio_b64", "input", "text",
        ],
    }


class DecisionLog:
    """In-memory, bounded store of :class:`DecisionRecord` (no persistence).

    A single session's audit trail. :meth:`record` appends; :attr:`records`
    returns an immutable snapshot (a tuple copy, so a caller cannot mutate the
    internal store); :attr:`last` is the most recent record or ``None``. No
    secrets are stored — see the module docstring.

    **Bounded memory.** The store is a ring buffer capped at ``max_records``
    (default :data:`DEFAULT_MAX_RECORDS`): once full, appending evicts the
    OLDEST record. The router appends one record per request and lives for the
    whole server session, so an unbounded list is a slow memory leak on a
    long-running service — a week of steady harness traffic is hundreds of
    thousands of records. The cap keeps the recent window an operator actually
    inspects; durable full-history storage is a separate (persistence) concern.
    Pass ``max_records=None`` for the old unbounded behaviour (tests,
    short-lived replay tooling).

    **Thread-safety.** The router runs under :class:`~http.server.ThreadingHTTPServer`,
    so :meth:`record` and :attr:`last`/:attr:`records`/:meth:`__len__` can be called
    concurrently from per-request handler threads. A :class:`threading.Lock` guards
    every mutation *and* every read that iterates ``_records``. The lock is held only
    for the minimal critical section (the deque operation itself); no expensive work
    is done under it.
    """

    def __init__(
        self,
        max_records: Optional[int] = DEFAULT_MAX_RECORDS,
        *,
        sink: Optional[Callable[[DecisionRecord], None]] = None,
    ) -> None:
        if max_records is not None and max_records <= 0:
            raise ValueError(f"max_records must be positive or None, got {max_records!r}")
        # deque(maxlen=None) is unbounded — the explicit opt-out.
        self._records: Deque[DecisionRecord] = deque(maxlen=max_records)
        self._lock = threading.Lock()
        # ADR-0033: optional durable sink (JSONL writer). Best-effort — a sink
        # failure never fails the request that produced the record.
        self._sink = sink

    def record(self, record: DecisionRecord) -> None:
        """Append ``record`` to the log, stamping ``unix_ts`` (thread-safe)."""
        record = _sanitize_replica_scheduler(
            _sanitize_replica_metadata(_sanitize_workload_metadata(record))
        )
        if not record.unix_ts:
            record = dataclasses.replace(record, unix_ts=time.time())
        with self._lock:
            self._records.append(record)
        if self._sink is not None:
            try:
                self._sink(record)
            except Exception as exc:
                print(
                    "[anvil] warning decision sink write failed: %s" % type(exc).__name__,
                    file=sys.stderr,
                    flush=True,
                )

    @property
    def capacity(self) -> Optional[int]:
        """The ring-buffer cap, or ``None`` when unbounded."""
        return self._records.maxlen

    @property
    def records(self) -> Tuple[DecisionRecord, ...]:
        """Immutable snapshot of all recorded decisions, oldest first (thread-safe)."""
        with self._lock:
            return tuple(self._records)

    def recent(self, limit: int = 512) -> Tuple[DecisionRecord, ...]:
        """Return at most 512 newest records, ordered oldest to newest."""
        if isinstance(limit, bool) or not isinstance(limit, int) or not 1 <= limit <= 512:
            raise ValueError("decision recent limit must be an integer from 1 to 512")
        with self._lock:
            newest_first = tuple(islice(reversed(self._records), limit))
        return tuple(reversed(newest_first))

    @property
    def last(self) -> Optional[DecisionRecord]:
        """The most recently recorded decision, or ``None`` if the log is empty (thread-safe)."""
        with self._lock:
            return self._records[-1] if self._records else None

    def __len__(self) -> int:
        with self._lock:
            return len(self._records)

    def summary(self, *, limit: int = 20) -> dict:
        """Safe recent-decision summary over the current immutable snapshot."""
        return summarize_decisions(self.records, limit=limit)


#: Default size cap for one :class:`DecisionLogWriter` generation before the
#: single-rotation ``os.replace`` to ``<path>.1``.
DEFAULT_DECISION_LOG_MAX_BYTES = 64 * 1024 * 1024


class DecisionLogWriter:
    """Append-only, size-capped JSONL sink for decision records (ADR-0033).

    One JSON object per line, from the record's own metadata-only fields.
    Absent optional workload fields are omitted to preserve the legacy shape;
    present workload fields are validated before serialization. The
    no-prompt/no-response/no-credential guarantee is the record contract's.
    Rotation keeps exactly one previous generation (``<path>.1``).

    Construction fails when the path is unwritable — a configured evidence
    sink that cannot write is a boot error, not a silent downgrade. Later
    write failures are reported by the caller and never fail requests.
    """

    def __init__(
        self, path: str, *, max_bytes: int = DEFAULT_DECISION_LOG_MAX_BYTES
    ) -> None:
        if max_bytes < 1024:
            raise ValueError("decision log max_bytes must be at least 1024")
        self.path = path
        self.max_bytes = int(max_bytes)
        self._lock = threading.Lock()
        directory = os.path.dirname(os.path.abspath(path))
        if not os.path.isdir(directory):
            raise OSError("decision log directory does not exist: %s" % directory)
        with open(path, "a", encoding="utf-8"):
            pass

    def __call__(self, record: DecisionRecord) -> None:
        record = _sanitize_replica_scheduler(
            _sanitize_replica_metadata(_sanitize_workload_metadata(record))
        )
        # Explicit schema: future dataclass fields (including subclasses) must
        # never silently become durable audit payloads through asdict recursion.
        payload = {
            name: getattr(record, name)
            for name in (
                "kind", "requested_tier", "served_tier", "total_prompt_tokens",
                "total_completion_tokens", "route", "request_id",
                "gateway_request_id", "workbench_run_id", "task_id",
                "request_bytes", "response_bytes", "latency_ms",
                "readiness_check_ms", "upstream_duration_ms",
                "time_to_first_content_ms", "finish_reason", "prompt_tokens_source",
                "completion_tokens_source", "output_limit_requested",
                "output_limit_applied", "output_limit_clamped", "unix_ts",
                "workload_created_at", "workload_updated_at", "workload_outcome",
            )
        }
        payload["attempts"] = [
            {name: getattr(attempt, name) for name in (
                "tier_id", "succeeded", "reason", "prompt_tokens",
                "completion_tokens", "outcome",
            )}
            for attempt in record.attempts
        ]
        payload.update(_replica_metadata(record))
        scheduler = _replica_scheduler_metadata(record)
        if scheduler is not None:
            payload["replica_scheduler"] = scheduler
        for field_name in (
            "workload_created_at", "workload_updated_at", "workload_outcome",
        ):
            if payload[field_name] is None:
                del payload[field_name]
        line = json.dumps(payload, sort_keys=True, separators=(",", ":"), allow_nan=False)
        with self._lock:
            self._rotate_if_needed()
            with open(self.path, "a", encoding="utf-8") as handle:
                handle.write(line + "\n")
                handle.flush()

    def _rotate_if_needed(self) -> None:
        try:
            size = os.path.getsize(self.path)
        except OSError:
            return
        if size < self.max_bytes:
            return
        os.replace(self.path, self.path + ".1")


def _sanitize_workload_metadata(record: DecisionRecord) -> DecisionRecord:
    """Drop malformed optional workload metadata before memory or sink writes."""
    created = record.workload_created_at
    updated = record.workload_updated_at
    outcome = record.workload_outcome
    valid = (
        type(created) is str
        and type(updated) is str
        and type(outcome) is str
        and len(created) == 27
        and len(updated) == 27
        and len(outcome) <= 12
        and _WORKLOAD_TIMESTAMP_RE.fullmatch(created) is not None
        and _WORKLOAD_TIMESTAMP_RE.fullmatch(updated) is not None
        and created <= updated
        and outcome in _WORKLOAD_OUTCOMES
    )
    if valid:
        try:
            datetime.strptime(created, "%Y-%m-%dT%H:%M:%S.%fZ")
            datetime.strptime(updated, "%Y-%m-%dT%H:%M:%S.%fZ")
        except (TypeError, ValueError):
            valid = False
    if created is None and updated is None and outcome is None:
        return record
    if valid:
        return record
    return dataclasses.replace(
        record,
        workload_created_at=None,
        workload_updated_at=None,
        workload_outcome=None,
    )
