"""Command declarations for the voice family."""

from .family import command_family
from .common import CONFIRM_OPTIONS
from .spec import CommandNode, _node, _handler, _option, _remote, _resource_node


@command_family(category="Voice")
def commands() -> CommandNode:
    return _node(
        "voice",
        "Manage audio and realtime proxy operations.",
        children=(
            _resource_node(
                "up",
                "Start the co-located managed voice stack.",
                "anvil_serving.voice.cli",
                role="stt-serve",
                options=CONFIRM_OPTIONS,
                coowned_roles=("tts-serve", "realtime-proxy"),
                mutation="mutate",
                argv_prefix=("up",),
                execution_runtime_roles=("docker",),
                docs_anchor="docs/cli/voice.md#co-located-stack-lifecycle",
            ),
            _resource_node(
                "down",
                "Stop the co-located managed voice stack.",
                "anvil_serving.voice.cli",
                role="stt-serve",
                options=CONFIRM_OPTIONS,
                coowned_roles=("tts-serve", "realtime-proxy"),
                mutation="mutate",
                argv_prefix=("down",),
                execution_runtime_roles=("docker",),
                docs_anchor="docs/cli/voice.md#co-located-stack-lifecycle",
            ),
            _node(
                "audio",
                "Manage topology-owned STT/TTS lifecycle.",
                children=(
                    _resource_node(
                        "up",
                        "Start audio serves.",
                        "anvil_serving.voice.cli",
                        role="stt-serve",
                        options=CONFIRM_OPTIONS,
                        coowned_roles=("tts-serve",),
                        mutation="mutate",
                        argv_prefix=("audio", "up"),
                        forward_resolution_options=True,
                        remote_operation=_remote(
                            "voice_manage",
                            fixed=(("action", "up"),),
                            allowed=("config", "profile", "dry_run", "timeout_seconds"),
                        ),
                    ),
                    _resource_node(
                        "down",
                        "Stop audio serves.",
                        "anvil_serving.voice.cli",
                        role="stt-serve",
                        options=CONFIRM_OPTIONS,
                        coowned_roles=("tts-serve",),
                        mutation="mutate",
                        argv_prefix=("audio", "down"),
                        forward_resolution_options=True,
                        remote_operation=_remote(
                            "voice_manage",
                            fixed=(("action", "down"),),
                            allowed=("config", "profile", "dry_run", "timeout_seconds"),
                        ),
                    ),
                    _resource_node(
                        "status",
                        "Show bounded audio serve status.",
                        "anvil_serving.voice.cli",
                        role="stt-serve",
                        coowned_roles=("tts-serve",),
                        argv_prefix=("audio", "status"),
                        forward_resolution_options=True,
                        remote_operation=_remote(
                            "voice_manage",
                            fixed=(("action", "status"),),
                            allowed=("config", "profile", "ready_timeout", "timeout_seconds"),
                        ),
                    ),
                    _resource_node(
                        "logs",
                        "Show bounded audio serve logs.",
                        "anvil_serving.voice.cli",
                        role="stt-serve",
                        coowned_roles=("tts-serve",),
                        argv_prefix=("audio", "logs"),
                        forward_resolution_options=True,
                        remote_operation=_remote(
                            "voice_manage",
                            fixed=(("action", "logs"),),
                            allowed=("config", "profile", "tail", "timeout_seconds"),
                        ),
                    ),
                ),
                docs_anchor="docs/cli/voice.md#audio-lifecycle",
            ),
            _node(
                "proxy",
                "Manage the realtime proxy process.",
                children=(
                    _resource_node(
                        "run",
                        "Run the realtime proxy.",
                        "anvil_serving.voice.cli",
                        role="realtime-proxy",
                        coowned_roles=("stt-proxy", "tts-proxy"),
                        mutation="process",
                        argv_prefix=("proxy", "run"),
                        forward_resolution_options=True,
                        output_policy="foreground",
                        execution_runtime_roles=("native",),
                    ),
                    _resource_node(
                        "up",
                        "Start the realtime proxy.",
                        "anvil_serving.voice.cli",
                        role="realtime-proxy",
                        options=CONFIRM_OPTIONS,
                        coowned_roles=("stt-proxy", "tts-proxy"),
                        mutation="mutate",
                        argv_prefix=("proxy", "up"),
                        forward_resolution_options=True,
                        remote_operation=_remote(
                            "voice_proxy_manage",
                            fixed=(("action", "up"),),
                            allowed=(
                                "config",
                                "profile",
                                "pid_file",
                                "log_file",
                                "dry_run",
                                "timeout_seconds",
                            ),
                        ),
                        execution_runtime_roles=("native",),
                    ),
                    _resource_node(
                        "down",
                        "Stop the realtime proxy.",
                        "anvil_serving.voice.cli",
                        role="realtime-proxy",
                        options=CONFIRM_OPTIONS,
                        coowned_roles=("stt-proxy", "tts-proxy"),
                        mutation="mutate",
                        argv_prefix=("proxy", "down"),
                        forward_resolution_options=True,
                        remote_operation=_remote(
                            "voice_proxy_manage",
                            fixed=(("action", "down"),),
                            allowed=(
                                "config",
                                "profile",
                                "pid_file",
                                "log_file",
                                "dry_run",
                                "timeout_seconds",
                            ),
                        ),
                        execution_runtime_roles=("native",),
                    ),
                    _resource_node(
                        "restart",
                        "Restart the realtime proxy.",
                        "anvil_serving.voice.cli",
                        role="realtime-proxy",
                        options=CONFIRM_OPTIONS,
                        coowned_roles=("stt-proxy", "tts-proxy"),
                        mutation="mutate",
                        argv_prefix=("proxy", "restart"),
                        forward_resolution_options=True,
                        remote_operation=_remote(
                            "voice_proxy_manage",
                            fixed=(("action", "restart"),),
                            allowed=(
                                "config",
                                "profile",
                                "pid_file",
                                "log_file",
                                "dry_run",
                                "timeout_seconds",
                            ),
                        ),
                        execution_runtime_roles=("native",),
                    ),
                    _resource_node(
                        "status",
                        "Show realtime proxy status.",
                        "anvil_serving.voice.cli",
                        role="realtime-proxy",
                        coowned_roles=("stt-proxy", "tts-proxy"),
                        argv_prefix=("proxy", "status"),
                        forward_resolution_options=True,
                        remote_operation=_remote(
                            "voice_proxy_manage",
                            fixed=(("action", "status"),),
                            allowed=(
                                "config",
                                "profile",
                                "pid_file",
                                "log_file",
                                "timeout_seconds",
                            ),
                        ),
                        execution_runtime_roles=("native",),
                    ),
                    _resource_node(
                        "logs",
                        "Show bounded realtime proxy logs.",
                        "anvil_serving.voice.cli",
                        role="realtime-proxy",
                        coowned_roles=("stt-proxy", "tts-proxy"),
                        argv_prefix=("proxy", "logs"),
                        forward_resolution_options=True,
                        remote_operation=_remote(
                            "voice_proxy_manage",
                            fixed=(("action", "logs"),),
                            allowed=(
                                "config",
                                "profile",
                                "pid_file",
                                "log_file",
                                "tail",
                                "timeout_seconds",
                            ),
                        ),
                        execution_runtime_roles=("native",),
                    ),
                    _resource_node(
                        "bridge",
                        "Run the Mini-to-Dark audio bridge.",
                        "anvil_serving.voice.cli",
                        role="realtime-proxy",
                        options=(
                            _option(
                                "--dry-run", summary="Render bridge routes without binding sockets."
                            ),
                        ),
                        coowned_roles=("stt-proxy", "tts-proxy"),
                        mutation="process",
                        argv_prefix=("proxy", "bridge"),
                        forward_resolution_options=True,
                        output_policy="foreground",
                        execution_runtime_roles=("native",),
                    ),
                ),
                docs_anchor="docs/cli/voice.md#realtime-proxy",
            ),
            _node(
                "benchmark",
                "Benchmark a voice session or multi-sample STT corpus.",
                handler=_handler(
                    "anvil_serving.voice.cli",
                    argv_prefix=("benchmark",),
                ),
                docs_anchor="docs/cli/voice.md#benchmark",
            ),
            _node(
                "corpus",
                "Prepare or validate an STT benchmark corpus.",
                children=(
                    _node(
                        "prepare",
                        "Build the deterministic English STT corpus.",
                        handler=_handler(
                            "anvil_serving.voice.cli",
                            argv_prefix=("corpus", "prepare"),
                        ),
                    ),
                    _node(
                        "validate",
                        "Validate STT corpus JSONL, audio, and hashes.",
                        handler=_handler(
                            "anvil_serving.voice.cli",
                            argv_prefix=("corpus", "validate"),
                        ),
                    ),
                ),
                docs_anchor="docs/cli/voice.md#stt-corpus",
            ),
            _node(
                "profiles",
                "Inspect voice profiles.",
                children=(
                    _node(
                        "list",
                        "List voice profiles.",
                        handler=_handler(
                            "anvil_serving.voice.cli",
                            attribute="main_profiles_list",
                            argv_prefix=(),
                        ),
                    ),
                    _node(
                        "validate",
                        "Validate the profile selected by --profile.",
                        handler=_handler(
                            "anvil_serving.voice.cli",
                            attribute="main_profiles_validate",
                            argv_prefix=(),
                        ),
                    ),
                ),
                docs_anchor="docs/cli/voice.md#profiles",
            ),
            _node(
                "sidecar",
                "Manage the speech-to-speech sidecar.",
                children=(
                    _node(
                        "validate",
                        "Validate a sidecar manifest.",
                        handler=_handler("anvil_serving.voice_sidecar", argv_prefix=("validate",)),
                    ),
                    _node(
                        "command",
                        "Render a sidecar command.",
                        handler=_handler("anvil_serving.voice_sidecar", argv_prefix=("command",)),
                    ),
                    _node(
                        "compose",
                        "Render sidecar compose configuration.",
                        handler=_handler("anvil_serving.voice_sidecar", argv_prefix=("compose",)),
                    ),
                ),
                docs_anchor="docs/cli/voice.md#speech-to-speech-sidecar",
            ),
        ),
        docs_anchor="docs/cli/voice.md",
    )
