"""anvil-serving init (alias: onboard) — generate a consistent local bring-up (genericity:T006).

Detects GPUs (`gpus.py`), picks a model from a `models sync` catalog (or an
explicit `--model`), and writes four mutually-consistent files into the CWD:

  ./docker-compose.yml   the SGLang/vLLM serve (via `deploy.render()`)
  ./serves.toml          the `[[serve]]` entry for `anvil-serving serves`
  ./router.toml          a `[router]` config: ONE tier, every preset routed to it
  ./operator-topology.toml  generic local command/resource ownership

The generated serving files agree on served-name and port — `tier.model == served-name`, the
tier's `base_url` port == the compose's published port, and `serves.toml`'s
container/port == the compose (the exact drift class genericity:T001/T009
exist to catch never has a chance to happen here, because `init` calls the
SAME `deploy.render()`/`deploy.append_serve_entry()`/`deploy.render_tier_stub()`
that `deploy` itself uses). Emitted serves bind loopback by default (T008).
GPU pinning falls back with a printed warning (never a silent mis-pin) when
`nvidia-smi` is absent (T007).
"""
import argparse
import json
import os
import sys
import time
import tomllib

from . import deploy as _deploy
from . import edge as _edge
from . import guard
from .paths import config_home
from .router import intent as _intent
from .topology import TopologyValidationError, parse_topology


class InitError(Exception):
    """Raised when `init` cannot proceed (no model found, etc.)."""


# --------------------------------------------------------------------------- #
# init --home: scaffold the FULL operational config set into ~/.anvil-serving
# --------------------------------------------------------------------------- #
# The single-file `init` above is the one-model quick start. `init --home`
# scaffolds the whole operational set — every manifest, compose file, topology,
# .env template, and the tailnet-edge config — so a fresh machine can run
# `anvil-serving serves up --group voice` (or any group) with zero hand-assembly.
#
# Source of truth: the shipped reference instance under examples/fakoli-dark/
# (and the reference voice manifest under examples/voice/). The set is COPIED
# from those canonical files at scaffold time — not hand-duplicated here — so it
# stays in lockstep with the reference example. Real host-specific values (the
# reference machine's two GPU UUIDs and its tailnet address) are rewritten to
# clearly-marked placeholders on the way out; secrets are never written (the
# scaffold ships `.env.example`, whose values are empty, never `.env`).
_HERE = os.path.dirname(os.path.abspath(__file__))
_EXAMPLES_DIR = os.path.join(_HERE, os.pardir, "examples")
_FAKOLI_DARK = os.path.join(_EXAMPLES_DIR, "fakoli-dark")
_VOICE_DIR = os.path.join(_EXAMPLES_DIR, "voice")

# (real value in the reference instance, clearly-marked placeholder). Applied to
# every scaffolded file so one machine's identity never rides onto a fresh host.
_SANITIZE = (
    ("GPU-d0f446cf-1771-414c-e116-a39138798a8c", "GPU-REPLACE-WITH-HEAVY-GPU-UUID"),
    ("GPU-04d3b6e7-5691-3e86-1d34-c37999440cf1", "GPU-REPLACE-WITH-FAST-GPU-UUID"),
    ("100.87.34.66", "REPLACE-WITH-YOUR-TAILNET-IP"),
)

# Destination filename -> canonical source file (copied through _sanitize).
# `edge.toml` is generated from edge.py's canonical routes (see below), so it is
# not listed here.
_HOME_SET = (
    ("serves.toml", os.path.join(_FAKOLI_DARK, "serves.toml")),
    ("serves.voice.toml", os.path.join(_FAKOLI_DARK, "serves.voice.toml")),
    ("serves.comfyui.toml", os.path.join(_FAKOLI_DARK, "serves.comfyui.toml")),
    ("docker-compose.yml", os.path.join(_FAKOLI_DARK, "docker-compose.yml")),
    ("docker-compose.voice-audio.yml",
     os.path.join(_FAKOLI_DARK, "docker-compose.voice-audio.yml")),
    ("docker-compose.comfyui.yml",
     os.path.join(_FAKOLI_DARK, "docker-compose.comfyui.yml")),
    ("operator-topology.toml", os.path.join(_FAKOLI_DARK, "operator-topology.toml")),
    (".env.example", os.path.join(_FAKOLI_DARK, ".env.example")),
    ("voice.toml", os.path.join(_VOICE_DIR, "voice.example.toml")),
)


def _sanitize(text):
    """Rewrite the reference machine's host-specific values to placeholders."""
    for real, placeholder in _SANITIZE:
        text = text.replace(real, placeholder)
    return text


def render_edge_config():
    """Render an ADR-0019 tailnet-edge config from edge.py's canonical route map.

    Generated (not copied) so the scaffolded `edge.toml` stays in lockstep with
    `anvil-serving edge {render,up,down}` — the routes come straight from
    `edge.DEFAULT_ROUTES`.
    """
    lines = [
        "# anvil-serving tailnet edge config (ADR-0019) — generated by `init --home`.",
        "# `anvil-serving edge {render,status,up,down}` path-routes the host's single",
        "# MagicDNS name to local services. Additive + idempotent; `down` removes only",
        "# the mounts it manages, never an operator-set `tailscale serve` mapping.",
        "# See docs/adr/0019-anvil-serving-owns-the-tailnet-edge.md.",
        "[edge]",
        f"https_port = {_edge.DEFAULT_HTTPS_PORT}",
        f'host = "{_edge.DEFAULT_TARGET_HOST}"   # default target host for port-only routes (loopback)',
        "",
        "[edge.routes]",
    ]
    for mount, port in _edge.DEFAULT_ROUTES:
        lines.append(f'"{mount}" = {port}')
    lines.append('# "/dashboard" = 8766   # extensible: add future dashboards under the same name')
    return "\n".join(lines) + "\n"


def _home_plan():
    """Build the ordered (dest_name, text) list for the home scaffold.

    Reads + sanitizes every canonical source, then appends the generated
    `edge.toml`. Raises InitError if any canonical source is missing (e.g. a
    wheel install without the shipped examples tree) — fail loud, never write a
    partial set.
    """
    missing = [src for _, src in _HOME_SET if not os.path.isfile(src)]
    if missing:
        raise InitError(
            "cannot scaffold the home config set — the shipped reference examples "
            "are not available next to this install (missing: %s). Run `init --home` "
            "from a source checkout of anvil-serving."
            % ", ".join(sorted(os.path.basename(s) for s in missing)))
    plan = []
    for dest_name, src in _HOME_SET:
        with open(src, encoding="utf-8") as f:
            plan.append((dest_name, _sanitize(f.read())))
    plan.append(("edge.toml", render_edge_config()))
    return plan


def scaffold_home(out_dir=None):
    """Scaffold the full operational config set into `out_dir`.

    `out_dir` defaults to the operator config home (`~/.anvil-serving`, honoring
    ANVIL_SERVING_HOME) — the default search dir for `serves up` etc. — so a
    fresh machine is operational with no path juggling; pass an explicit dir to
    override (e.g. a temp dir for verification).

    Every file is backed up (guard.backup_file → numbered `.anvil.bak.N`) before
    it is overwritten, exactly like single-file `init`: an existing operator file
    is NEVER clobbered silently, and a backup that cannot be written aborts the
    whole scaffold rather than proceeding without a revert path. Returns a dict
    describing what was written for the CLI to report and tests to assert on.
    """
    target = os.path.abspath(os.path.expanduser(out_dir)) if out_dir else config_home()
    plan = _home_plan()  # validate + read everything before touching the target

    os.makedirs(target, exist_ok=True)
    written, backed_up = [], []
    for dest_name, text in plan:
        dest = os.path.join(target, dest_name)
        try:
            bak = guard.backup_file(dest)
        except OSError as e:
            raise InitError(
                "could not back up existing %s before rewriting it (%s); fix or "
                "remove the file and re-run — refusing to overwrite without a backup"
                % (dest_name, e)) from e
        if bak:
            backed_up.append((dest, bak))
        with open(dest, "w", encoding="utf-8") as f:
            f.write(text)
        written.append(dest)

    return {"out_dir": target, "written": written, "backed_up": backed_up}


def _read_catalog(catalog_dir):
    """[{**card fields}, ...] read from `<catalog_dir>/cards/*.json` (written
    by `anvil-serving models sync`). [] if the catalog dir/cards are absent —
    never raises (a missing catalog just means "nothing to auto-pick")."""
    cards_dir = os.path.join(catalog_dir, "cards")
    if not os.path.isdir(cards_dir):
        return []
    out = []
    for fn in sorted(os.listdir(cards_dir)):
        if not fn.endswith(".json"):
            continue
        try:
            with open(os.path.join(cards_dir, fn), encoding="utf-8") as f:
                out.append(json.load(f))
        except Exception:
            continue
    return out


def pick_model(catalog, explicit_model=None):
    """Choose a model to deploy.

    `explicit_model` (a local dir path) always wins. Otherwise pick the
    largest `sglang_loadable` (and not sm_120-hazardous) catalog entry — a
    coding harness wants the biggest model that safely loads — falling back
    to any safetensors entry if none is marked loadable. Returns a facts dict
    (`local_path` at minimum) or None if nothing qualifies.
    """
    if explicit_model:
        name = os.path.basename(os.path.normpath(explicit_model)) or explicit_model
        return {"local_path": explicit_model, "id": name}
    candidates = [
        c for c in catalog
        if c.get("local_path") and c.get("sglang_loadable") and not c.get("sm120_caveat")
    ]
    if not candidates:
        candidates = [c for c in catalog if c.get("local_path") and c.get("format") == "safetensors"]
    if not candidates:
        return None
    candidates.sort(key=lambda c: c.get("size_gb") or 0, reverse=True)
    return candidates[0]


def _served_name(model_facts):
    raw = model_facts.get("id") or model_facts.get("repo") or model_facts.get("local_path") or "local-specialist"
    base = os.path.basename(str(raw).rstrip("/\\")) or "local-specialist"
    return _deploy._slug(base).lower()


def render_router_config(tier_id, served_name, port, context_limit=131072,
                          mapping_version=None, disable_thinking=False):
    """A complete, loadable `[router]` config: one tier, every preset routed
    to it. Loads clean through `router.config.load()` with NO T001
    missing-`model` warning, because `model` is always set here."""
    mapping_version = mapping_version or time.strftime("%Y-%m-%d.0")
    tier_block = _deploy.render_tier_stub(
        tier_id, served_name, port, context_limit=context_limit,
        disable_thinking=disable_thinking)
    presets_lines = "\n".join(f'{p.id:<12} = ["{tier_id}"]' for p in _intent.PRESETS)
    return (
        "# anvil-serving router config — generated by `anvil-serving init`.\n"
        "# See configs/example.toml for the full annotated reference; add a\n"
        "# second tier + reorder [router.presets] pools once you have one.\n"
        "[router]\n"
        f'mapping_version = "{mapping_version}"\n'
        f"{tier_block}\n"
        "[router.presets]\n"
        f"{presets_lines}\n"
    )


def render_starter_topology(port=30000):
    """Render deterministic local ownership without inspecting machine identity.

    OS and GPU identity intentionally remain absent. A deployment overlay must
    declare those facts before OS-specific repair or GPU-bound target resolution.
    """
    return (
        "# Generic local topology generated by `anvil-serving init`.\n"
        "# This base file contains no machine identity, GPU UUIDs, or credentials.\n"
        "# Add deployment-specific addresses, host OS, GPU roles, and authenticated\n"
        "# controllers in a separate overlay; do not infer them from the current host.\n"
        "schema_version = 1\n"
        'id = "local-starter"\n'
        'command_host = "host:local-host"\n'
        'command_runtime = "runtime:local-native"\n\n'
        "[[capacity_policies]]\n"
        'id = "local-model-capable"\n'
        "allow_model_workloads = true\n\n"
        "[[hosts]]\n"
        'id = "local-host"\n'
        'roles = ["operator", "router", "serve"]\n'
        'address = "127.0.0.1"\n'
        'capacity_policy = "local-model-capable"\n\n'
        "[[runtimes]]\n"
        'id = "local-native"\n'
        'host = "local-host"\n'
        'role = "native"\n\n'
        "[[runtimes]]\n"
        'id = "local-docker"\n'
        'host = "local-host"\n'
        'role = "docker"\n\n'
        "[[resources]]\n"
        'id = "local-host-resource"\n'
        'role = "host"\n'
        'host = "local-host"\n'
        'runtime = "local-native"\n'
        'workload = "service"\n\n'
        "[[resources]]\n"
        'id = "local-router"\n'
        'role = "router"\n'
        'host = "local-host"\n'
        'runtime = "local-docker"\n'
        'endpoint = "http://127.0.0.1:8000/v1"\n'
        'endpoint_kind = "host-relative-loopback"\n'
        'workload = "service"\n\n'
        "[[resources]]\n"
        'id = "local-model-serve"\n'
        'role = "model-serve"\n'
        'host = "local-host"\n'
        'runtime = "local-docker"\n'
        f'endpoint = "http://127.0.0.1:{port}/v1"\n'
        'endpoint_kind = "host-relative-loopback"\n'
        'workload = "llm"\n\n'
        "[[resources]]\n"
        'id = "local-model-catalog"\n'
        'role = "model-catalog"\n'
        'host = "local-host"\n'
        'runtime = "local-native"\n'
        'workload = "model"\n\n'
        "[[resources]]\n"
        'id = "local-evaluation"\n'
        'role = "evaluation"\n'
        'host = "local-host"\n'
        'runtime = "local-native"\n'
        'workload = "service"\n'
    )


def run(model=None, gpu="0", catalog_dir="./model-library", out_dir=".",
        served_name=None, tier_id=None, port=30000, context=131072,
        engine=None, disable_thinking=False, bind=_deploy.LOOPBACK_BIND,
        _run=None):
    """Generate compose, manifests, router config, and topology into `out_dir`.

    Returns a dict describing what was written, for the CLI to report and for
    tests to assert against without parsing stdout. Raises `InitError` if no
    model can be resolved.
    """
    catalog = _read_catalog(catalog_dir)
    facts = pick_model(catalog, model)
    if facts is None:
        raise InitError(
            f"no model found: pass --model <local dir>, or run "
            f"`anvil-serving models sync --out {catalog_dir}` first to build a catalog."
        )
    model_path = model or facts["local_path"]
    served = served_name or _served_name(facts)
    tid = tier_id or served
    disable_th = disable_thinking or bool(facts.get("thinking_default"))
    render_kwargs = {}
    if _run is not None:
        render_kwargs["_run"] = _run
    eng = engine or _deploy._infer_engine(model_path)
    topology_text = render_starter_topology(port=port)
    try:
        parse_topology(tomllib.loads(topology_text))
    except (tomllib.TOMLDecodeError, TopologyValidationError) as exc:
        raise InitError(f"could not generate a valid starter topology ({exc})") from exc

    os.makedirs(out_dir, exist_ok=True)
    compose_out = os.path.join(out_dir, "docker-compose.yml")
    manifest_out = os.path.join(out_dir, "serves.toml")
    router_out = os.path.join(out_dir, "router.toml")
    topology_out = os.path.join(out_dir, "operator-topology.toml")

    # Guard: these are operator-editable configs — never clobber hand edits
    # without a numbered .anvil.bak.N sibling to revert to (same convention as
    # `host wsl-config`). Fail CLOSED but clean: if the backup cannot be
    # written, refuse to overwrite rather than proceeding without a revert
    # path (or dying with a raw traceback).
    for existing in (compose_out, router_out, topology_out):
        try:
            bak = guard.backup_file(existing)
        except OSError as e:
            raise InitError(
                f"could not back up existing {os.path.basename(existing)} before "
                f"rewriting it ({e}); fix or remove the file and re-run — refusing "
                f"to overwrite without a backup")
        if bak:
            print(f"[anvil-serving] backed up existing {os.path.basename(existing)} "
                  f"-> {os.path.basename(bak)}")

    compose_text = _deploy.render(
        model_path, gpu, context, served, port=port, bind=bind, engine=eng,
        disable_thinking=disable_th, **render_kwargs)
    with open(compose_out, "w", encoding="utf-8") as f:
        f.write(compose_text)

    service = "vllm" if eng == "vllm" else "sglang"
    container = f"vllm-{_deploy._slug(served)}" if eng == "vllm" else "sglang"
    # forward-slash: spliced into a TOML string then shlex-split (T009 note).
    compose_rel = compose_out.replace(os.sep, "/")
    up = f"docker compose -f {compose_rel} up -d {service}"
    _deploy.append_serve_entry(manifest_out, tid, container, port, served, up, engine=eng)

    router_text = render_router_config(
        tid, served, port, context_limit=context, disable_thinking=disable_th)
    with open(router_out, "w", encoding="utf-8") as f:
        f.write(router_text)

    try:
        with open(topology_out, "w", encoding="utf-8") as f:
            f.write(topology_text)
    except OSError as exc:
        raise InitError(f"could not write the starter topology ({exc})") from exc

    return {
        "model_path": model_path, "served_name": served, "tier_id": tid,
        "engine": eng, "port": port, "compose": compose_out,
        "manifest": manifest_out, "router": router_out, "topology": topology_out,
        "disable_thinking": disable_th,
    }


def main(argv):
    ap = argparse.ArgumentParser(
        prog="anvil-serving init",
        description="Detect GPUs + a local model, and write a consistent "
                    "./docker-compose.yml + ./serves.toml + ./router.toml + "
                    "./operator-topology.toml bring-up "
                    "(alias: onboard).")
    ap.add_argument("--model", default=None,
                    help="local model dir mounted into the container "
                         "(default: pick the biggest loadable entry from --catalog-dir)")
    ap.add_argument("--catalog-dir", default="./model-library",
                    help="`anvil-serving models sync` output dir to auto-pick a "
                         "model from (default: %(default)s)")
    ap.add_argument("--gpu", default="0", help="GPU index or GPU-UUID (default: %(default)s)")
    ap.add_argument("--served-name", default=None,
                    help="served-model-name (default: derived from the model id)")
    ap.add_argument("--tier-id", default=None, help="router tier id (default: --served-name)")
    ap.add_argument("--port", type=int, default=30000)
    ap.add_argument("--context", type=int, default=131072)
    ap.add_argument("--engine", choices=["sglang", "vllm"], default=None,
                    help="serving engine (default: inferred from the model's weight format)")
    ap.add_argument("--disable-thinking", action="store_true",
                    help="force-disable a thinking-by-default model (default: "
                         "auto from the catalog's thinking_default)")
    ap.add_argument("--bind", default=None, help="publish address (default: 127.0.0.1)")
    ap.add_argument("--expose-lan", action="store_true", help="shorthand for --bind 0.0.0.0")
    ap.add_argument("--home", action="store_true",
                    help="scaffold the FULL operational config set (all manifests, "
                         "compose files, topology, .env.example, tailnet-edge config) "
                         "into ~/.anvil-serving so `serves up --group NAME` works with "
                         "zero hand-assembly (default --out-dir: the config home)")
    ap.add_argument("--out-dir", default=None,
                    help="where to write the files (default: CWD; with --home, the "
                         "operator config home ~/.anvil-serving)")
    a = ap.parse_args(argv)

    if a.home:
        return _main_home(a)

    bind = a.bind or (_deploy.LAN_BIND if a.expose_lan else _deploy.LOOPBACK_BIND)

    try:
        result = run(
            model=a.model, gpu=a.gpu, catalog_dir=a.catalog_dir, out_dir=a.out_dir or ".",
            served_name=a.served_name, tier_id=a.tier_id, port=a.port,
            context=a.context, engine=a.engine, disable_thinking=a.disable_thinking,
            bind=bind)
    except InitError as e:
        print(f"[anvil-serving] {e}", file=sys.stderr)
        return 2

    print("wrote:")
    print("  " + result["compose"])
    print("  " + result["manifest"])
    print("  " + result["router"])
    print("  " + result["topology"])
    print()
    print("model:  " + result["model_path"])
    print("engine: " + result["engine"])
    print("tier:   %s (served-model-name %r, port %s)"
          % (result["tier_id"], result["served_name"], result["port"]))
    print()
    print("Remaining manual steps:")
    print("  1. Add a deployment overlay for real host OS, addresses, GPU roles, or controllers.")
    print("     Keep operator-topology.toml as the generic base; validate both with `topology validate`.")
    print("  2. anvil-serving serves up            # docker compose up -d, per serves.toml")
    print("  3. anvil-serving serves status         # wait for it to report healthy")
    print("  4. anvil-serving router run --config %s" % result["router"])
    print("  5. Point your harness at http://127.0.0.1:8000 (ANTHROPIC_BASE_URL) and set")
    print("     ANTHROPIC_MODEL to a preset (planning / quick-edit / review / chat / long-context).")
    print("     For OpenClaw: see docs/OPENCLAW-INTEGRATION-SPEC.md for the provider adapter.")
    print("  6. If this is a cloud-fallback setup, see configs/example-with-cloud.toml + "
          "docs/adr/0001-cloud-cost-and-subscription-auth.md (off by default; opt-in only).")
    return 0


def _main_home(a):
    """`init --home`: scaffold the full operational config set into the config home."""
    try:
        result = scaffold_home(out_dir=a.out_dir)
    except InitError as e:
        print(f"[anvil-serving] {e}", file=sys.stderr)
        return 2

    print("scaffolded the operational config set into %s:" % result["out_dir"])
    for path in result["written"]:
        print("  " + os.path.basename(path))
    if result["backed_up"]:
        print()
        print("backed up existing operator files before overwrite:")
        for path, bak in result["backed_up"]:
            print("  %s -> %s" % (os.path.basename(path), os.path.basename(bak)))
    print()
    print("Host-specific values are clearly-marked placeholders - edit before bring-up:")
    print("  - GPU UUIDs: GPU-REPLACE-WITH-*-GPU-UUID in the compose files "
          "(`nvidia-smi -L`), or set *_GPU_UUID in .env.")
    print("  - Tailnet address: REPLACE-WITH-YOUR-TAILNET-IP (this host's tailnet IP).")
    print("  - Secrets: copy .env.example -> .env and fill it in (never committed).")
    print()
    print("Next steps (zero hand-assembly):")
    print("  1. cp %s/.env.example %s/.env   # then fill in host values"
          % (result["out_dir"], result["out_dir"]))
    print("  2. anvil-serving serves groups          # see the resolvable groups")
    print("  3. anvil-serving serves up --group voice   # (or llm-stack / comfy / ...)")
    print("  4. anvil-serving serves status")
    print("  5. anvil-serving router run             # front door on 127.0.0.1:8000")
    print("  6. Optional tailnet edge (ADR-0019): anvil-serving edge render "
          "--config %s/edge.toml" % result["out_dir"])
    return 0
