"""anvil-serving init (alias: onboard) — generate a consistent local bring-up (genericity:T006).

Detects GPUs (`gpus.py`), picks a model from a `models sync` catalog (or an
explicit `--model`), and writes four mutually-consistent files into the CWD:

  ./docker-compose.yml   the SGLang/vLLM serve (via `deploy.render()`)
  ./serves.toml          the `[[serve]]` entry for `anvil-serving serves`
  ./router.toml          a `[router]` config: ONE tier, every preset routed to it
  ./operator-topology.toml  generic local command/resource ownership

The generated serving files agree on served-name and port — `tier.model == served-name`, the
tier's `base_url` port == the compose's published port, and `serves.toml`'s
container/port == the compose (the exact drift class genericity:T001/T009
exist to catch never has a chance to happen here, because `init` calls the
SAME `deploy.render()`/`deploy.append_serve_entry()`/`deploy.render_tier_stub()`
that `deploy` itself uses). Emitted serves bind loopback by default (T008).
GPU pinning falls back with a printed warning (never a silent mis-pin) when
`nvidia-smi` is absent (T007).
"""
import argparse
import json
import os
import sys
import time
import tomllib

from . import deploy as _deploy
from . import guard
from .router import intent as _intent
from .topology import TopologyValidationError, parse_topology


class InitError(Exception):
    """Raised when `init` cannot proceed (no model found, etc.)."""


def _read_catalog(catalog_dir):
    """[{**card fields}, ...] read from `<catalog_dir>/cards/*.json` (written
    by `anvil-serving models sync`). [] if the catalog dir/cards are absent —
    never raises (a missing catalog just means "nothing to auto-pick")."""
    cards_dir = os.path.join(catalog_dir, "cards")
    if not os.path.isdir(cards_dir):
        return []
    out = []
    for fn in sorted(os.listdir(cards_dir)):
        if not fn.endswith(".json"):
            continue
        try:
            with open(os.path.join(cards_dir, fn), encoding="utf-8") as f:
                out.append(json.load(f))
        except Exception:
            continue
    return out


def pick_model(catalog, explicit_model=None):
    """Choose a model to deploy.

    `explicit_model` (a local dir path) always wins. Otherwise pick the
    largest `sglang_loadable` (and not sm_120-hazardous) catalog entry — a
    coding harness wants the biggest model that safely loads — falling back
    to any safetensors entry if none is marked loadable. Returns a facts dict
    (`local_path` at minimum) or None if nothing qualifies.
    """
    if explicit_model:
        name = os.path.basename(os.path.normpath(explicit_model)) or explicit_model
        return {"local_path": explicit_model, "id": name}
    candidates = [
        c for c in catalog
        if c.get("local_path") and c.get("sglang_loadable") and not c.get("sm120_caveat")
    ]
    if not candidates:
        candidates = [c for c in catalog if c.get("local_path") and c.get("format") == "safetensors"]
    if not candidates:
        return None
    candidates.sort(key=lambda c: c.get("size_gb") or 0, reverse=True)
    return candidates[0]


def _served_name(model_facts):
    raw = model_facts.get("id") or model_facts.get("repo") or model_facts.get("local_path") or "local-specialist"
    base = os.path.basename(str(raw).rstrip("/\\")) or "local-specialist"
    return _deploy._slug(base).lower()


def render_router_config(tier_id, served_name, port, context_limit=131072,
                          mapping_version=None, disable_thinking=False):
    """A complete, loadable `[router]` config: one tier, every preset routed
    to it. Loads clean through `router.config.load()` with NO T001
    missing-`model` warning, because `model` is always set here."""
    mapping_version = mapping_version or time.strftime("%Y-%m-%d.0")
    tier_block = _deploy.render_tier_stub(
        tier_id, served_name, port, context_limit=context_limit,
        disable_thinking=disable_thinking)
    presets_lines = "\n".join(f'{p.id:<12} = ["{tier_id}"]' for p in _intent.PRESETS)
    return (
        "# anvil-serving router config — generated by `anvil-serving init`.\n"
        "# See configs/example.toml for the full annotated reference; add a\n"
        "# second tier + reorder [router.presets] pools once you have one.\n"
        "[router]\n"
        f'mapping_version = "{mapping_version}"\n'
        f"{tier_block}\n"
        "[router.presets]\n"
        f"{presets_lines}\n"
    )


def render_starter_topology(port=30000):
    """Render deterministic local ownership without inspecting machine identity.

    OS and GPU identity intentionally remain absent. A deployment overlay must
    declare those facts before OS-specific repair or GPU-bound target resolution.
    """
    return (
        "# Generic local topology generated by `anvil-serving init`.\n"
        "# This base file contains no machine identity, GPU UUIDs, or credentials.\n"
        "# Add deployment-specific addresses, host OS, GPU roles, and authenticated\n"
        "# controllers in a separate overlay; do not infer them from the current host.\n"
        "schema_version = 1\n"
        'id = "local-starter"\n'
        'command_host = "host:local-host"\n'
        'command_runtime = "runtime:local-native"\n\n'
        "[[capacity_policies]]\n"
        'id = "local-model-capable"\n'
        "allow_model_workloads = true\n\n"
        "[[hosts]]\n"
        'id = "local-host"\n'
        'roles = ["operator", "router", "serve"]\n'
        'address = "127.0.0.1"\n'
        'capacity_policy = "local-model-capable"\n\n'
        "[[runtimes]]\n"
        'id = "local-native"\n'
        'host = "local-host"\n'
        'role = "native"\n\n'
        "[[runtimes]]\n"
        'id = "local-docker"\n'
        'host = "local-host"\n'
        'role = "docker"\n\n'
        "[[resources]]\n"
        'id = "local-host-resource"\n'
        'role = "host"\n'
        'host = "local-host"\n'
        'runtime = "local-native"\n'
        'workload = "service"\n\n'
        "[[resources]]\n"
        'id = "local-router"\n'
        'role = "router"\n'
        'host = "local-host"\n'
        'runtime = "local-docker"\n'
        'endpoint = "http://127.0.0.1:8000/v1"\n'
        'endpoint_kind = "host-relative-loopback"\n'
        'workload = "service"\n\n'
        "[[resources]]\n"
        'id = "local-model-serve"\n'
        'role = "model-serve"\n'
        'host = "local-host"\n'
        'runtime = "local-docker"\n'
        f'endpoint = "http://127.0.0.1:{port}/v1"\n'
        'endpoint_kind = "host-relative-loopback"\n'
        'workload = "llm"\n\n'
        "[[resources]]\n"
        'id = "local-model-catalog"\n'
        'role = "model-catalog"\n'
        'host = "local-host"\n'
        'runtime = "local-native"\n'
        'workload = "model"\n\n'
        "[[resources]]\n"
        'id = "local-evaluation"\n'
        'role = "evaluation"\n'
        'host = "local-host"\n'
        'runtime = "local-native"\n'
        'workload = "service"\n'
    )


def run(model=None, gpu="0", catalog_dir="./model-library", out_dir=".",
        served_name=None, tier_id=None, port=30000, context=131072,
        engine=None, disable_thinking=False, bind=_deploy.LOOPBACK_BIND,
        _run=None):
    """Generate compose, manifests, router config, and topology into `out_dir`.

    Returns a dict describing what was written, for the CLI to report and for
    tests to assert against without parsing stdout. Raises `InitError` if no
    model can be resolved.
    """
    catalog = _read_catalog(catalog_dir)
    facts = pick_model(catalog, model)
    if facts is None:
        raise InitError(
            f"no model found: pass --model <local dir>, or run "
            f"`anvil-serving models sync --out {catalog_dir}` first to build a catalog."
        )
    model_path = model or facts["local_path"]
    served = served_name or _served_name(facts)
    tid = tier_id or served
    disable_th = disable_thinking or bool(facts.get("thinking_default"))
    render_kwargs = {}
    if _run is not None:
        render_kwargs["_run"] = _run
    eng = engine or _deploy._infer_engine(model_path)

    os.makedirs(out_dir, exist_ok=True)
    compose_out = os.path.join(out_dir, "docker-compose.yml")
    manifest_out = os.path.join(out_dir, "serves.toml")
    router_out = os.path.join(out_dir, "router.toml")
    topology_out = os.path.join(out_dir, "operator-topology.toml")

    # Guard: these are operator-editable configs — never clobber hand edits
    # without a numbered .anvil.bak.N sibling to revert to (same convention as
    # `host wsl-config`). Fail CLOSED but clean: if the backup cannot be
    # written, refuse to overwrite rather than proceeding without a revert
    # path (or dying with a raw traceback).
    for existing in (compose_out, router_out, topology_out):
        try:
            bak = guard.backup_file(existing)
        except OSError as e:
            raise InitError(
                f"could not back up existing {os.path.basename(existing)} before "
                f"rewriting it ({e}); fix or remove the file and re-run — refusing "
                f"to overwrite without a backup")
        if bak:
            print(f"[anvil-serving] backed up existing {os.path.basename(existing)} "
                  f"-> {os.path.basename(bak)}")

    compose_text = _deploy.render(
        model_path, gpu, context, served, port=port, bind=bind, engine=eng,
        disable_thinking=disable_th, **render_kwargs)
    with open(compose_out, "w", encoding="utf-8") as f:
        f.write(compose_text)

    service = "vllm" if eng == "vllm" else "sglang"
    container = f"vllm-{_deploy._slug(served)}" if eng == "vllm" else "sglang"
    # forward-slash: spliced into a TOML string then shlex-split (T009 note).
    compose_rel = compose_out.replace(os.sep, "/")
    up = f"docker compose -f {compose_rel} up -d {service}"
    _deploy.append_serve_entry(manifest_out, tid, container, port, served, up, engine=eng)

    router_text = render_router_config(
        tid, served, port, context_limit=context, disable_thinking=disable_th)
    with open(router_out, "w", encoding="utf-8") as f:
        f.write(router_text)

    topology_text = render_starter_topology(port=port)
    try:
        # Validate the exact generated document before replacing any existing
        # operator topology.
        parse_topology(tomllib.loads(topology_text))
        with open(topology_out, "w", encoding="utf-8") as f:
            f.write(topology_text)
    except (OSError, tomllib.TOMLDecodeError, TopologyValidationError) as exc:
        raise InitError(f"could not write a valid starter topology ({exc})") from exc

    return {
        "model_path": model_path, "served_name": served, "tier_id": tid,
        "engine": eng, "port": port, "compose": compose_out,
        "manifest": manifest_out, "router": router_out, "topology": topology_out,
        "disable_thinking": disable_th,
    }


def main(argv):
    ap = argparse.ArgumentParser(
        prog="anvil-serving init",
        description="Detect GPUs + a local model, and write a consistent "
                    "./docker-compose.yml + ./serves.toml + ./router.toml + "
                    "./operator-topology.toml bring-up "
                    "(alias: onboard).")
    ap.add_argument("--model", default=None,
                    help="local model dir mounted into the container "
                         "(default: pick the biggest loadable entry from --catalog-dir)")
    ap.add_argument("--catalog-dir", default="./model-library",
                    help="`anvil-serving models sync` output dir to auto-pick a "
                         "model from (default: %(default)s)")
    ap.add_argument("--gpu", default="0", help="GPU index or GPU-UUID (default: %(default)s)")
    ap.add_argument("--served-name", default=None,
                    help="served-model-name (default: derived from the model id)")
    ap.add_argument("--tier-id", default=None, help="router tier id (default: --served-name)")
    ap.add_argument("--port", type=int, default=30000)
    ap.add_argument("--context", type=int, default=131072)
    ap.add_argument("--engine", choices=["sglang", "vllm"], default=None,
                    help="serving engine (default: inferred from the model's weight format)")
    ap.add_argument("--disable-thinking", action="store_true",
                    help="force-disable a thinking-by-default model (default: "
                         "auto from the catalog's thinking_default)")
    ap.add_argument("--bind", default=None, help="publish address (default: 127.0.0.1)")
    ap.add_argument("--expose-lan", action="store_true", help="shorthand for --bind 0.0.0.0")
    ap.add_argument("--out-dir", default=".", help="where to write the four files (default: CWD)")
    a = ap.parse_args(argv)
    bind = a.bind or (_deploy.LAN_BIND if a.expose_lan else _deploy.LOOPBACK_BIND)

    try:
        result = run(
            model=a.model, gpu=a.gpu, catalog_dir=a.catalog_dir, out_dir=a.out_dir,
            served_name=a.served_name, tier_id=a.tier_id, port=a.port,
            context=a.context, engine=a.engine, disable_thinking=a.disable_thinking,
            bind=bind)
    except InitError as e:
        print(f"[anvil-serving] {e}", file=sys.stderr)
        return 2

    print("wrote:")
    print("  " + result["compose"])
    print("  " + result["manifest"])
    print("  " + result["router"])
    print("  " + result["topology"])
    print()
    print("model:  " + result["model_path"])
    print("engine: " + result["engine"])
    print("tier:   %s (served-model-name %r, port %s)"
          % (result["tier_id"], result["served_name"], result["port"]))
    print()
    print("Remaining manual steps:")
    print("  1. Add a deployment overlay for real host OS, addresses, GPU roles, or controllers.")
    print("     Keep operator-topology.toml as the generic base; validate both with `topology validate`.")
    print("  2. anvil-serving serves up            # docker compose up -d, per serves.toml")
    print("  3. anvil-serving serves status         # wait for it to report healthy")
    print("  4. anvil-serving router run --config %s" % result["router"])
    print("  5. Point your harness at http://127.0.0.1:8000 (ANTHROPIC_BASE_URL) and set")
    print("     ANTHROPIC_MODEL to a preset (planning / quick-edit / review / chat / long-context).")
    print("     For OpenClaw: see docs/OPENCLAW-INTEGRATION-SPEC.md for the provider adapter.")
    print("  6. If this is a cloud-fallback setup, see configs/example-with-cloud.toml + "
          "docs/adr/0001-cloud-cost-and-subscription-auth.md (off by default; opt-in only).")
    return 0
