ARG BASE_IMAGE=vllm/vllm-openai@sha256:212a1bd7b4267c604408d17dc0048ef152101bc67fbe6ba8567899fc1f227bcd
FROM ${BASE_IMAGE}

COPY configs/kernel-tunes/vllm/f25953cc59f9b4ba9b04b16228d2b86dcfbcbdb1/nvidia-rtx-pro-6000-blackwell-max-q-workstation-edition/configs/ /opt/anvil/kernel-tunes/
